# Problem Statement 1:


In [99]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [100]:
data=pd.read_csv('D:\DBDA March 2022\Machine Learning\Exam\data.csv')

**Pre-Processing Data**

In [101]:
data

F     N  Prprice per square foot
0   0.44  0.68                   511.14
1   0.99  0.23                   717.10
2   0.84  0.29                   607.91
3   0.28  0.45                   270.40
4   0.07  0.83                   289.88
..   ...   ...                      ...
95  0.99  0.13                   636.22
96  0.28  0.46                   272.12
97  0.87  0.36                   696.65
98  0.23  0.87                   434.53
99  0.77  0.36                   593.86

[100 rows x 3 columns]

In [102]:
data.describe()

F           N  Prprice per square foot
count  100.000000  100.000000               100.000000
mean     0.550300    0.501700               554.214600
std      0.293841    0.307124               347.312796
min      0.010000    0.000000                42.080000
25%      0.300000    0.230000               278.172500
50%      0.570000    0.485000               514.285000
75%      0.822500    0.760000               751.752500
max      1.000000    0.990000              1563.820000

In [103]:
data.shape

(100, 3)

In [104]:
data.isnull().sum()

F                          0
N                          0
Prprice per square foot    0
dtype: int64

**Standardizing Data**

In [105]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
scaled = scalar.fit_transform(data)

In [106]:
data=pd.DataFrame(scaled)

In [107]:
data.head()

0         1         2
0 -0.377265  0.583471 -0.124647
1  1.503928 -0.889115  0.471350
2  0.990875 -0.692770  0.155381
3 -0.924521 -0.169184 -0.821290
4 -1.642794  1.074333 -0.764919

**Dependent & Independent Varibles Identification**

In [108]:
X=data.iloc[:,0:2].values
y=data.iloc[:,-1].values

In [109]:
X

array([[-0.37726457,  0.5834713 ],
       [ 1.50392777, -0.88911471],
       [ 0.99087531, -0.69276991],
       [-0.92452053, -0.16918377],
       [-1.64279397,  1.07433331],
       [ 0.37521236,  0.97616091],
       [ 0.61463684,  1.36885051],
       [ 0.06738089, -0.23463204],
       [-0.41146807,  1.27067811],
       [-0.95872402,  1.46702291],
       [-0.41146807, -1.44542499],
       [ 1.0934858 ,  1.33612638],
       [ 0.78565433,  0.61619544],
       [ 1.19609629,  1.43429878],
       [-0.47987506, -1.44542499],
       [-0.1036366 , -1.08545952],
       [-0.27465408,  0.51802304],
       [ 0.34100887, -0.23463204],
       [ 1.02507881,  0.45257477],
       [ 1.29870678, -0.20190791],
       [-0.47987506,  1.40157465],
       [-0.65089255, -0.23463204],
       [ 0.78565433,  1.13978158],
       [ 0.47782285, -1.41270085],
       [-1.74540446,  0.05988516],
       [-1.30075899, -1.15090778],
       [ 0.44361936, -1.21635605],
       [ 0.99087531,  0.32167823],
       [-0.58248556,

In [110]:
y

array([-0.1246473 ,  0.47135029,  0.15538128, -0.82128965, -0.76491932,
        0.80051481,  1.40021641, -0.28655284,  0.24873379, -0.1248788 ,
       -1.09147947,  1.99178655,  0.97564481,  2.27305944, -1.11216981,
       -0.80493994, -0.10644559, -0.09249769,  1.09382572,  0.8595474 ,
        0.24856016, -0.71051675,  1.42325069, -0.6418769 , -1.10646912,
       -1.28674999, -0.55630859,  0.92020048, -0.72492764, -0.86186008,
       -0.61641186,  1.85320467, -0.42137284,  0.98771176, -0.10407271,
        0.24462466, -0.7301364 , -1.13097921, -0.90703159,  2.58943358,
        0.15853547, -1.09854023,  0.1135376 , -0.57370005,  0.33927935,
        1.85051347, -0.79675062, -0.41327033, -1.48199158, -1.12284776,
       -1.43412889,  0.25533155, -0.53845413,  0.42991173,  0.17803938,
       -1.18766785, -1.28834156, -0.65379917, -1.01007817,  2.33316272,
        1.01748849, -0.19354758, -1.01702318, -1.01919349, -1.17296758,
        0.55295415, -0.14808671,  2.92154973, -1.12568364, -0.33

**Test Train Split**

In [111]:
from sklearn.model_selection import train_test_split

In [112]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state=7)

In [113]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((80, 2), (20, 2), (80,), (20,))

**Multiple Linear Regression Model Building**

In [114]:
from sklearn.linear_model import LinearRegression

In [115]:
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [116]:
y_pred=regressor.predict(X_test)

In [117]:
y_pred

array([-1.27362836, -0.40846515,  1.41748862,  0.7617318 , -1.24193001,
       -0.72231347, -0.89741863,  0.77730993, -1.43263286,  1.22003199,
        1.68613102,  0.3143363 , -0.23437572,  0.91241493, -0.51706776,
        1.46217201,  1.55518671,  0.11064841,  0.47022517,  0.98723885])

**1 = 180.38
2 = 1312.07
3 = 440.13
4 = 343.72**

In [172]:
regressor.predict([[1.503928,0.889115]])

array([1.58562342])

In [173]:
regressor.predict([[-1.642794,1.074333]])

array([-0.55238493])

In [175]:
data.isnull().sum()

0    0
1    0
2    0
dtype: int64

# Problem Statement 2:

In [216]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [217]:
dataset = {
'Id':[1,2,3,4,5,6,7,8,9,10,11,12,13,14],
'Age':['<21','<21','21-35','>35','>35','>35','21-35','<21','<21','>35','<21','21-35','21-35','>35'],
'Income':['High','High','High','Medium','Low','Low','Low','Medium','Low','Medium','Medium','Medium','High','Medium'],
'Gender':['Male','Male','Male','Male','Female','Female','Female','Male','Female','Female','Female','Male','Female','Male'],
'MaritalStatus':['Single','Married','Single','Single','Single','Married','Married','Single','Married','Single','Married','Married','Single','Married'],
'Buys':['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']}

In [218]:
df = pd.DataFrame(dataset,columns=['Id','Age','Income','Gender','MaritalStatus','Buys'])

In [219]:
df

Id    Age  Income  Gender MaritalStatus Buys
0    1    <21    High    Male        Single   No
1    2    <21    High    Male       Married   No
2    3  21-35    High    Male        Single  Yes
3    4    >35  Medium    Male        Single  Yes
4    5    >35     Low  Female        Single  Yes
5    6    >35     Low  Female       Married   No
6    7  21-35     Low  Female       Married  Yes
7    8    <21  Medium    Male        Single   No
8    9    <21     Low  Female       Married  Yes
9   10    >35  Medium  Female        Single  Yes
10  11    <21  Medium  Female       Married  Yes
11  12  21-35  Medium    Male       Married  Yes
12  13  21-35    High  Female        Single  Yes
13  14    >35  Medium    Male       Married   No

In [220]:
df.head()

Id    Age  Income  Gender MaritalStatus Buys
0   1    <21    High    Male        Single   No
1   2    <21    High    Male       Married   No
2   3  21-35    High    Male        Single  Yes
3   4    >35  Medium    Male        Single  Yes
4   5    >35     Low  Female        Single  Yes

In [221]:
df.shape

(14, 6)

In [222]:
df.describe()

Id
count  14.0000
mean    7.5000
std     4.1833
min     1.0000
25%     4.2500
50%     7.5000
75%    10.7500
max    14.0000

In [223]:
df["Buys"].value_counts()

Yes    9
No     5
Name: Buys, dtype: int64

In [224]:
df

Id    Age  Income  Gender MaritalStatus Buys
0    1    <21    High    Male        Single   No
1    2    <21    High    Male       Married   No
2    3  21-35    High    Male        Single  Yes
3    4    >35  Medium    Male        Single  Yes
4    5    >35     Low  Female        Single  Yes
5    6    >35     Low  Female       Married   No
6    7  21-35     Low  Female       Married  Yes
7    8    <21  Medium    Male        Single   No
8    9    <21     Low  Female       Married  Yes
9   10    >35  Medium  Female        Single  Yes
10  11    <21  Medium  Female       Married  Yes
11  12  21-35  Medium    Male       Married  Yes
12  13  21-35    High  Female        Single  Yes
13  14    >35  Medium    Male       Married   No

In [225]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df = df.apply(le.fit_transform)

In [226]:
df

Id  Age  Income  Gender  MaritalStatus  Buys
0    0    1       0       1              1     0
1    1    1       0       1              0     0
2    2    0       0       1              1     1
3    3    2       2       1              1     1
4    4    2       1       0              1     1
5    5    2       1       0              0     0
6    6    0       1       0              0     1
7    7    1       2       1              1     0
8    8    1       1       0              0     1
9    9    2       2       0              1     1
10  10    1       2       0              0     1
11  11    0       2       1              0     1
12  12    0       0       0              1     1
13  13    2       2       1              0     0

In [227]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [228]:
X

array([[ 0,  1,  0,  1,  1],
       [ 1,  1,  0,  1,  0],
       [ 2,  0,  0,  1,  1],
       [ 3,  2,  2,  1,  1],
       [ 4,  2,  1,  0,  1],
       [ 5,  2,  1,  0,  0],
       [ 6,  0,  1,  0,  0],
       [ 7,  1,  2,  1,  1],
       [ 8,  1,  1,  0,  0],
       [ 9,  2,  2,  0,  1],
       [10,  1,  2,  0,  0],
       [11,  0,  2,  1,  0],
       [12,  0,  0,  0,  1],
       [13,  2,  2,  1,  0]], dtype=int64)

In [229]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [230]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25, random_state=0)

In [231]:
X_train.shape , X_test.shape , y_train.shape , y_test.shape

((10, 5), (4, 5), (10,), (4,))

In [232]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [233]:
y_pred=classifier.predict(X_test)

In [234]:
y_pred

array([0, 1, 0, 1])

In [235]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm=confusion_matrix(y_test,y_pred)
cm

array([[0, 0],
       [2, 2]], dtype=int64)

In [236]:
accuracy_score(y_test,y_pred)

0.5

In [213]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.50      0.67         4

    accuracy                           0.50         4
   macro avg       0.50      0.25      0.33         4
weighted avg       1.00      0.50      0.67         4



C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**Concluding Statement**

**Root Node for the decision tree is 'Age'**
**The accuracy for this model is 50%.**